### ISSUE TITLE
Hardware platform and GUI examples

### ISSUE THREAD

**Issue by elektronchika** [andsmedeiros/uevloop#2]
Hi André,

first I would like to say great job!

Could you provide some examples for using the uevloop on real hardware like stm32 development board or other? Do you plan on integrating some kind of graphical library for creating user interfaces?

Thank you!
Lazar

**Comment by andsmedeiros** [comment]
Thank you, @elektronchika! I don't have real life code here with me, but in the [application](https://github.com/andsmedeiros/uevloop#application) section you can find a realistic example. The only platform-specific code you'll have to write is the 1kHz ISR. 
About GUI libraries, this is not on my thoughts right now.
