### ISSUE TITLE
Capacity error reporting is missing

### ISSUE THREAD

**Issue by hilt0n** [andsmedeiros/uevloop#4]
First of all, thank you for this great library. It makes firmware really easy, more clean and is way simpler than RTOS which are not always required.

That being said, after having used this library for a professional project and doing continuous improvement in the firmware, I had multiple very strange issues which has been fixed by increasing the event queue size and/or the scheduler queue size.

It's really a problem because when overflow happens, there is no way to monitor that because all the functions pushing events to queues are not returning error in case of overflow. That's clearly an issue and doesn't really fit the required quality level for a professional firmware. 

Just wanted to know then if you plan to improve this aspect ? If not, is this repo still active and will you support me eventually if I make pull request to improve this aspect ?

**Comment by andsmedeiros** [comment]
Hello, @hilt0n! Thank you for the feedback, it is really appreciated!
Event tough I really love this project and am proud of it, I haven't had lately much time to work on it. I saw you even opened a PR regarding critical sections which I didn't respond, sorry for that. 
That said, the project definitely can use a well intended collaborator. Can you elaborate a little on what you plan to implement?

**Comment by lucasasselli** [comment]
Hi @andsmedeiros , I have been using uevloop for the last few months (amazing tool BTW, you are an absolute pro) and I stumbled upon the same/ asimilar problem: when using `uel_evloop_enqueue_closure`, if the queue is full, a null event is returned by `uel_syspools_acquire_event`, leading to all sort of troubles. 

A better solution could be adding a null pointer check and have the function return pass or fail. It's a relatively small change: I might try to implement it myself in the coming weeks, but I'm still playing around with the library. What do you think?

**Comment by andsmedeiros** [comment]
Thanks for the compliments, @lucasasselli! I'm glad my work is useful to others!

I'm not exactly sure what you mean by fail (calling `exit()`?), but I think the system as  whole lacks some sort of exception handling mechanism. I put "application signals" in the roadmap because on first thought it felt like the correct way to handle asynchronous exceptions, but as signals are asynchronous themselves, they are unsuitable to recover from exceptions from the library.
We could get around that by implementing synchronous signal emission or by implementing hooks in the core components (namely the scheduler and event loop), but these are not trivial, albeit not hard either.
How do you feel about this?

**Comment by lucasasselli** [comment]
Could it be simply returning 1 or 0 from the function? Is the queue is full, nothing is done and a 1 is returned.  In this way the program knows that something went wrong and some action can be taken.

**Comment by andsmedeiros** [comment]
It is a valid workaround, but I don't think this approach has much synergy with the API. The library itself acts as a microkernel that manages itself and userland code is run through inversion of control. This makes awkward to expose the library state to the code that consumes its API and cumbersome to check every return value.
If the library had a sync handler for this kind of situation, however, it could try to recover itself and keep the user code running as if nothing happened.

**Comment by hilt0n** [comment]
I was also thinking to return value but at the same time not really convinced because I don't want to manage the possible errors everywhere in my code. 
In our case, we need to ensure the code is safe but we don't want to add extra logic to manage edge cases, just detect them and increase the queue size if needed as we can expect some relative determinism.

While it seems to be difficult to create async event for error handling (egg and chicken problem), it really makes sense to create sync callback (at least in our use case) to detect these events. I would also think to a queue watermark which keeps track of the max used amount of each queue (exported by the API). During the dev and later for a release, we can then test the firmware, generate events and verify that we are not too close from an overflow. 

To come back to the return value approach, I understand your position but don't fully agree. A lot a information is returned from kernel (or RTOS) to notify user application that something went wrong (device not accessible, broken pipe, mem. alloc failure, etc) in which case the application needs to react accordingly. This is not what I would do with your library in my particular case but this is still legitimate IMO.

**Comment by andsmedeiros** [comment]
@hilt0n I also can't think of any case that benefits from this. If the pools are depleted, it could be useful for externally buffering the data to be input later, when there are resources available again. Still, it's much simpler to just adjust the pool size.
I like the watermark idea. Between it and sync handlers on `syspools` and `sysqueues` we have good memory reporting and handling mechanisms. Handlers for trespassing a configurable threshold would be great also.

**Comment by lucasasselli** [comment]
Sync handler sounds good!

**Comment by andsmedeiros** [comment]
If you want to share any WIP also, please do!

I don't have a fixed standard, but I tend to follow some guidelines:
- exported symbols are always in the form uel_[module]_[descriptive name] (uppercase for macros and constants);
- function return types, params and brackets are in the same line;
- when lines are too long, prefer to break in parentheses/brackets sets, starting and ending at the same indentation;
- indent with 4 spaces;
- avoid bracketless if/while/for etc;

If you need any more assistance carrying this out, I will gladly help you. Just call out.

**Comment by andsmedeiros** [comment]
@hilt0n Have you made any progress on this? Do you need any assistance?
